# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 313dae07e3d725ef0a467f78396a0ed8a878d49066117dfd4a797ef527a136331a521230e87d65111ac2881a90d47af92ad3f72313e14b3b83c8cfd10ab5cc7a

test:
  secret_key_base: 10f23d0643dc92fd3da9edd4826ad02d5e48b7af06eda06ea9e28e362ef231ab3377b79f4aaac2c683108e18b51962c1502d503f98df88633ed922a3904b288a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
